'use client';

import { useState } from 'react';
import { ArrowRight, Check, ChevronRight, CircleHelp, Gavel, Laptop, MessageSquare, RotateCcw, Scale, ShieldCheck, Sparkles } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Slider } from '@/components/ui/slider';
import { Textarea } from '@/components/ui/textarea';

type Condition = 'none' | 'factual' | 'empathetic' | 'voice';
type Mode = 'researcher' | 'participant';
const conditions: { id: Condition; name: string; detail: string }[] = [
  { id: 'none', name: 'No explanation', detail: 'Outcome only' },
  { id: 'factual', name: 'Factual', detail: 'Reason for allocation' },
  { id: 'empathetic', name: 'Empathetic', detail: 'Reason + acknowledgment' },
  { id: 'voice', name: 'Voice', detail: 'Reason + acknowledgment + appeal' },
];
const explanation: Record<Condition, React.ReactNode> = {
  none: <p>The other agent was selected.</p>,
  factual: <p>The other project was prioritized because its deadline is tomorrow and a delay would affect four team members.</p>,
  empathetic: <><p>The other project was prioritized because its deadline is tomorrow and a delay would affect four team members.</p><p className="mt-3 text-slate-600">We know this delays your work and may feel frustrating.</p></>,
  voice: <><p>The other project was prioritized because its deadline is tomorrow and a delay would affect four team members.</p><p className="mt-3 text-slate-600">We know this delays your work and may feel frustrating. You can add context before the decision is finalized.</p></>,
};

export default function Home() {
  const [stage, setStage] = useState<'brief' | 'decision' | 'appeal' | 'survey' | 'done'>('brief');
  const [condition, setCondition] = useState<Condition>('voice');
  const [mode, setMode] = useState<Mode>('researcher');
  const [priority, setPriority] = useState('Deadline urgency');
  const [note, setNote] = useState('');
  const [ratings, setRatings] = useState({ frustration: 4, fairness: 4, trust: 4 });
  const reset = () => { setStage('brief'); setCondition(mode === 'participant' ? conditions[Math.floor(Math.random() * conditions.length)].id : 'voice'); setPriority('Deadline urgency'); setNote(''); setRatings({ frustration: 4, fairness: 4, trust: 4 }); };
  const changeMode = (nextMode: Mode) => { setMode(nextMode); setStage('brief'); setCondition(nextMode === 'participant' ? conditions[Math.floor(Math.random() * conditions.length)].id : 'voice'); setPriority('Deadline urgency'); setNote(''); setRatings({ frustration: 4, fairness: 4, trust: 4 }); };

  return <main className="min-h-screen bg-[#f6f7fb] text-slate-900">
    <header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-6xl items-center justify-between gap-4 px-5 py-4 sm:px-8"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-xl bg-indigo-600 text-white"><Scale className="size-5" /></span><div><p className="font-semibold tracking-tight">FairSignal</p><p className="text-xs text-slate-500">Multi-agent decision study prototype</p></div></div><div className="flex items-center gap-2"><div className="hidden rounded-lg bg-slate-100 p-1 sm:flex"><button onClick={() => changeMode('participant')} className={`rounded-md px-2.5 py-1.5 text-xs font-medium ${mode === 'participant' ? 'bg-white text-indigo-700 shadow-sm' : 'text-slate-500'}`}>Participant mode</button><button onClick={() => changeMode('researcher')} className={`rounded-md px-2.5 py-1.5 text-xs font-medium ${mode === 'researcher' ? 'bg-white text-indigo-700 shadow-sm' : 'text-slate-500'}`}>Researcher mode</button></div><Button variant="ghost" size="sm" onClick={reset}><RotateCcw /> Start over</Button></div></div></header>
    <div className={`mx-auto grid max-w-6xl gap-6 px-5 py-7 sm:px-8 ${mode === 'researcher' ? 'lg:grid-cols-[220px_1fr]' : 'lg:grid-cols-1'}`}>
      {mode === 'researcher' && <aside className="rounded-2xl border border-slate-200 bg-white p-4 lg:h-fit"><p className="mb-3 text-xs font-semibold uppercase tracking-wider text-slate-500">Demo condition</p><div className="grid grid-cols-2 gap-2 lg:grid-cols-1">{conditions.map((item) => <button key={item.id} onClick={() => { setCondition(item.id); if (stage !== 'brief') setStage('decision'); }} className={`rounded-xl border p-3 text-left transition ${condition === item.id ? 'border-indigo-600 bg-indigo-50 ring-1 ring-indigo-600' : 'border-slate-200 hover:border-slate-300'}`}><p className="text-sm font-medium">{item.name}</p><p className="mt-0.5 text-xs text-slate-500">{item.detail}</p></button>)}</div><p className="mt-4 text-xs leading-relaxed text-slate-500">Researcher mode is for comparing the four conditions. In participant mode, the app assigns one condition at random and hides it.</p></aside>}
      <section className="min-h-[590px] rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-9"><div className="mb-8 flex items-center gap-2 text-sm text-slate-500"><span className="font-medium text-indigo-700">{stage === 'brief' ? '1. Scenario' : stage === 'decision' || stage === 'appeal' ? '2. Decision' : '3. Response'}</span><ChevronRight className="size-4" /><span>{stage === 'survey' || stage === 'done' ? 'Measure reaction' : 'Shared-resource conflict'}</span></div>
        {stage === 'brief' && <><div className="max-w-2xl"><span className="mb-4 inline-flex items-center gap-2 rounded-full bg-indigo-50 px-3 py-1 text-xs font-semibold text-indigo-700"><Sparkles className="size-3.5" /> Workplace scenario</span><h1 className="text-3xl font-semibold tracking-tight sm:text-4xl">Two agents need one high-performance computer.</h1><p className="mt-4 text-lg leading-relaxed text-slate-600">Your AI agent requested the computer for your data-analysis project. Another employee&apos;s agent has made the same request.</p></div><div className="mt-9 grid gap-4 md:grid-cols-2"><AgentCard mine /><AgentCard /></div><div className="mt-8 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><CircleHelp className="mr-2 inline size-4" /><strong>Your task:</strong> Review the mediator&apos;s allocation. The decision process uses the same fair rule in every condition.</div><Button size="lg" className="mt-7 bg-indigo-600 px-5 hover:bg-indigo-700" onClick={() => setStage('decision')}>See mediator decision <ArrowRight /></Button></>}
        {stage === 'decision' && <><div className="max-w-2xl"><span className="inline-flex items-center gap-2 rounded-full bg-rose-50 px-3 py-1 text-xs font-semibold text-rose-700"><Gavel className="size-3.5" /> Allocation complete</span><h1 className="mt-4 text-3xl font-semibold tracking-tight">The other agent was selected.</h1><p className="mt-3 text-slate-600">Your request for the computer was not approved for the 2–5 PM slot.</p></div><div className="mt-8 rounded-2xl border border-slate-200 bg-slate-50 p-5"><div className="mb-4 flex items-center gap-2 text-sm font-semibold text-slate-700"><ShieldCheck className="size-5 text-emerald-600" /> Mediator explanation</div><div className="text-base leading-relaxed text-slate-800">{explanation[condition]}</div></div>{condition === 'voice' && <Button variant="outline" className="mt-5 border-indigo-200 text-indigo-700 hover:bg-indigo-50" onClick={() => setStage('appeal')}><MessageSquare /> Add context or request review</Button>}<Button size="lg" className="mt-8 bg-indigo-600 hover:bg-indigo-700" onClick={() => setStage('survey')}>Continue to check-in <ArrowRight /></Button></>}
        {stage === 'appeal' && <><h1 className="text-3xl font-semibold tracking-tight">Tell the mediator what matters.</h1><p className="mt-3 max-w-xl text-slate-600">Your input will be recorded before the decision is finalized. It may not change the outcome, but the mediator will respond to it.</p><div className="mt-8"><p className="mb-3 text-sm font-semibold">Your most important consideration</p><div className="grid gap-2 sm:grid-cols-2">{['Deadline urgency', 'Project impact', 'Accessibility need', 'Equal turn-taking'].map((item) => <button key={item} onClick={() => setPriority(item)} className={`rounded-xl border p-3 text-left text-sm ${priority === item ? 'border-indigo-600 bg-indigo-50 font-medium text-indigo-800' : 'border-slate-200'}`}>{priority === item && <Check className="mr-1 inline size-4" />}{item}</button>)}</div></div><div className="mt-6"><label className="mb-2 block text-sm font-semibold" htmlFor="context">Optional context</label><Textarea id="context" value={note} onChange={(event) => setNote(event.target.value)} placeholder="e.g., My analysis is blocking a client presentation tomorrow." /></div><div className="mt-6 rounded-2xl bg-emerald-50 p-4 text-sm leading-relaxed text-emerald-950"><strong>Review response:</strong> We considered <em>{priority.toLowerCase()}</em>. The other project remains first because its deadline is tomorrow and affects four team members. Your project has been reserved for the next available 5–8 PM slot.</div><Button size="lg" className="mt-7 bg-indigo-600 hover:bg-indigo-700" onClick={() => setStage('survey')}>Continue to check-in <ArrowRight /></Button></>}
        {stage === 'survey' && <><h1 className="text-3xl font-semibold tracking-tight">A quick check-in</h1><p className="mt-3 text-slate-600">There are no right answers. Your ratings help test whether the explanation affected your response.</p><div className="mt-8 space-y-7">{([{ key: 'frustration', question: 'How frustrated do you feel?', low: 'Not frustrated', high: 'Very frustrated' }, { key: 'fairness', question: 'How fair was this decision process?', low: 'Not fair', high: 'Very fair' }, { key: 'trust', question: 'How much do you trust your AI agent now?', low: 'Do not trust', high: 'Trust completely' }] as const).map((item) => <div key={item.key} className="rounded-2xl border border-slate-200 p-5"><div className="mb-4 flex justify-between gap-3"><p className="font-medium">{item.question}</p><span className="rounded-full bg-indigo-50 px-2.5 py-0.5 text-sm font-semibold text-indigo-700">{ratings[item.key]} / 7</span></div><Slider min={1} max={7} value={[ratings[item.key]]} onValueChange={(value) => setRatings({ ...ratings, [item.key]: value[0] })} /><div className="mt-2 flex justify-between text-xs text-slate-500"><span>{item.low}</span><span>{item.high}</span></div></div>)}</div><Button size="lg" className="mt-8 bg-indigo-600 hover:bg-indigo-700" onClick={() => setStage('done')}>Submit response <Check /></Button></>}
        {stage === 'done' && <div className="mx-auto max-w-xl py-16 text-center"><span className="mx-auto grid size-14 place-items-center rounded-full bg-emerald-100 text-emerald-700"><Check className="size-7" /></span><h1 className="mt-6 text-3xl font-semibold tracking-tight">Response recorded.</h1><p className="mt-3 text-slate-600">This prototype keeps the allocation fair and unfavorable, while changing only how the mediator communicates it. That lets researchers test whether explanation, empathy, and user voice change emotional response, fairness judgments, and trust.</p><Button variant="outline" className="mt-7" onClick={reset}>Try another condition</Button></div>}
      </section>
    </div>
  </main>;
}

function AgentCard({ mine = false }: { mine?: boolean }) { return <article className={`rounded-2xl border p-5 ${mine ? 'border-indigo-200 bg-indigo-50/50' : 'border-slate-200 bg-slate-50'}`}><div className="flex items-center gap-3"><span className={`grid size-10 place-items-center rounded-xl ${mine ? 'bg-indigo-600 text-white' : 'bg-slate-800 text-white'}`}><Laptop className="size-5" /></span><div><p className="font-semibold">{mine ? 'Your agent' : 'Other agent'}</p><p className="text-xs text-slate-500">{mine ? 'Data analysis project' : 'Release-blocking project'}</p></div></div><dl className="mt-5 space-y-2 text-sm"><div className="flex justify-between"><dt className="text-slate-500">Requested slot</dt><dd className="font-medium">2–5 PM</dd></div><div className="flex justify-between"><dt className="text-slate-500">Deadline</dt><dd className="font-medium">{mine ? 'In 3 days' : 'Tomorrow'}</dd></div><div className="flex justify-between"><dt className="text-slate-500">People affected</dt><dd className="font-medium">{mine ? '1' : '4'}</dd></div></dl></article>; }
