'use client';

import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';

type Condition = 'none' | 'factual' | 'empathetic' | 'voice';
type Mode = 'participant' | 'researcher';
type Score = 'frustration' | 'fairness' | 'trust' | 'clarity' | 'voice';
type Profile = { age: string; experience: string; baselineTrust: number; fairnessValue: string; importance: number };
type Response = Profile & Record<Score, number> & { id: number; condition: Condition; note: string };

const conditionLabels: Record<Condition, string> = { none: 'No explanation', factual: 'Factual explanation', empathetic: 'Empathetic explanation', voice: 'Explanation + voice' };
const randomCondition = (): Condition => (Object.keys(conditionLabels) as Condition[])[Math.floor(Math.random() * 4)];
const emptyProfile = (): Profile => ({ age: '', experience: '', baselineTrust: 4, fairnessValue: '', importance: 4 });
const emptyScores = (): Record<Score, number> => ({ frustration: 4, fairness: 4, trust: 4, clarity: 4, voice: 4 });

export default function Home() {
  const [mode, setMode] = useState<Mode>('researcher');
  const [stage, setStage] = useState<'profile' | 'scenario' | 'decision' | 'context' | 'checkin' | 'complete'>('profile');
  const [condition, setCondition] = useState<Condition>('voice');
  const [assignment, setAssignment] = useState<Condition | 'random'>('random');
  const [profile, setProfile] = useState<Profile>(emptyProfile());
  const [scores, setScores] = useState<Record<Score, number>>(emptyScores());
  const [note, setNote] = useState('');
  const [context, setContext] = useState('Deadline urgency');
  const [responses, setResponses] = useState<Response[]>([]);

  const startParticipant = () => { setMode('participant'); setStage('profile'); setCondition(assignment === 'random' ? randomCondition() : assignment); setProfile(emptyProfile()); setScores(emptyScores()); setNote(''); setContext('Deadline urgency'); };
  const submit = () => { setResponses((all) => [...all, { id: all.length + 1, condition, ...profile, ...scores, note }]); setStage('complete'); };

  return <main className="min-h-screen bg-[#FFFBF7] text-[#4D688C]">
    <header className="border-b border-[#4D688C] bg-[#E9F0FA]"><div className="mx-auto flex max-w-6xl items-center justify-between gap-4 px-5 py-5 sm:px-8"><p className="font-serif text-xl font-semibold">Experiment Prototype</p><div className="flex rounded-md border border-[#4D688C] bg-[#E9F0FA] p-0.5 text-sm"><button onClick={startParticipant} className={`rounded px-3 py-1.5 ${mode === 'participant' ? 'bg-[#4D688C] text-[#FFFBF7]' : 'text-[#4D688C] hover:bg-[#E9F0FA]'}`}>Participant view</button><button onClick={() => setMode('researcher')} className={`rounded px-3 py-1.5 ${mode === 'researcher' ? 'bg-[#4D688C] text-[#FFFBF7]' : 'text-[#4D688C] hover:bg-[#E9F0FA]'}`}>Researcher view</button></div></div></header>
    {mode === 'researcher' ? <Researcher responses={responses} onStart={startParticipant} assignment={assignment} setAssignment={setAssignment} /> : <div className="mx-auto grid max-w-6xl gap-6 px-5 py-7 sm:px-8 lg:grid-cols-[220px_1fr]"><ParticipantSidebar stage={stage} /><Participant stage={stage} condition={condition} profile={profile} setProfile={setProfile} scores={scores} setScores={setScores} note={note} setNote={setNote} context={context} setContext={setContext} setStage={setStage} onSubmit={submit} onRestart={startParticipant} /></div>}
  </main>;
}

function Researcher({ responses, onStart, assignment, setAssignment }: { responses: Response[]; onStart: () => void; assignment: Condition | 'random'; setAssignment: (value: Condition | 'random') => void }) {
  return <div className="mx-auto max-w-6xl px-5 py-10 sm:px-8"><div className="border-b-2 border-[#4D688C] pb-5"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-[#4D688C]">Researcher workspace</p><h1 className="mt-2 font-serif text-4xl">Response review</h1></div><div className="mt-7 grid gap-5 lg:grid-cols-[260px_1fr]"><aside className="border border-[#4D688C] bg-[#E9F0FA] p-5"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-[#4D688C]">Study setup</p><AssignmentControl assignment={assignment} setAssignment={setAssignment} /><dl className="mt-5 space-y-4 text-sm"><div><dt className="text-[#4D688C]">Design</dt><dd className="mt-1 font-medium">Randomly assigned condition</dd></div><div><dt className="text-[#4D688C]">Decision</dt><dd className="mt-1 font-medium">Fair but unfavorable</dd></div><div><dt className="text-[#4D688C]">Measures</dt><dd className="mt-1 font-medium">Affect, fairness, trust</dd></div></dl><Button className="mt-7 w-full rounded-sm bg-[#4D688C] hover:bg-[#4D688C]" onClick={onStart}>Begin session</Button></aside><section className="border border-[#4D688C] bg-[#E9F0FA]"><div className="flex items-end justify-between border-b border-[#4D688C] px-5 py-4"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-[#4D688C]">Recorded responses</p><p className="mt-1 text-sm text-[#4D688C]">Current browser session</p></div><p className="font-serif text-3xl">{responses.length}</p></div>{responses.length === 0 ? <p className="p-10 text-center text-sm text-[#4D688C]">No responses recorded.</p> : <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-[#E9F0FA] text-xs uppercase tracking-wide text-[#4D688C]"><tr><th className="px-5 py-3">ID</th><th className="px-5 py-3">Condition</th><th className="px-5 py-3">Age</th><th className="px-5 py-3">AI experience</th><th className="px-5 py-3">Frustration</th><th className="px-5 py-3">Fairness</th><th className="px-5 py-3">Trust</th><th className="px-5 py-3">Clarity</th></tr></thead><tbody>{responses.map((r) => <tr key={r.id} className="border-t border-[#4D688C]"><td className="px-5 py-4">{String(r.id).padStart(2, '0')}</td><td className="px-5 py-4 font-medium">{conditionLabels[r.condition]}</td><td className="px-5 py-4">{r.age}</td><td className="px-5 py-4">{r.experience}</td><td className="px-5 py-4">{r.frustration}/7</td><td className="px-5 py-4">{r.fairness}/7</td><td className="px-5 py-4">{r.trust}/7</td><td className="px-5 py-4">{r.clarity}/7</td></tr>)}</tbody></table></div>}</section></div></div>;
}

function Participant({ stage, condition, profile, setProfile, scores, setScores, note, setNote, context, setContext, setStage, onSubmit, onRestart }: { stage: 'profile' | 'scenario' | 'decision' | 'context' | 'checkin' | 'complete'; condition: Condition; profile: Profile; setProfile: (p: Profile) => void; scores: Record<Score, number>; setScores: (s: Record<Score, number>) => void; note: string; setNote: (v: string) => void; context: string; setContext: (v: string) => void; setStage: (s: 'profile' | 'scenario' | 'decision' | 'context' | 'checkin' | 'complete') => void; onSubmit: () => void; onRestart: () => void }) {
  const setScore = (key: Score, value: number) => setScores({ ...scores, [key]: value });
  const explanation = condition === 'none' ? 'The other agent was selected.' : 'The other project was prioritized because its deadline is tomorrow and delaying it would affect four team members.';
  const profileReady = Boolean(profile.age && profile.experience && profile.fairnessValue);
  return <div className="mx-auto max-w-3xl px-5 py-10 sm:px-8"><div className="mb-8 flex justify-between border-b border-[#4D688C] pb-4 text-xs font-semibold uppercase tracking-[0.15em] text-[#4D688C]"><span>Multi-agent allocation study</span><span>{stage === 'profile' ? '01 / Profile' : stage === 'scenario' ? '02 / Scenario' : stage === 'decision' || stage === 'context' ? '03 / Decision' : '04 / Check-in'}</span></div>
    {stage === 'profile' && <section><p className="text-xs font-semibold uppercase tracking-[0.15em] text-[#4D688C]">Participant profile</p><h1 className="mt-3 font-serif text-4xl">Before you begin</h1><p className="mt-4 text-[#4D688C]">Do not enter identifying information.</p><div className="mt-8 grid gap-6 border border-[#4D688C] bg-[#E9F0FA] p-5 sm:grid-cols-2"><Choice label="Age range" value={profile.age} options={['18–24', '25–34', '35–44', '45+']} onChange={(v) => setProfile({ ...profile, age: v })} /><Choice label="Experience using AI tools" value={profile.experience} options={['Rarely', 'Sometimes', 'Often', 'Very often']} onChange={(v) => setProfile({ ...profile, experience: v })} /><Choice label="Most important fairness principle" value={profile.fairnessValue} options={['Equal treatment', 'Urgent need', 'Greatest group benefit', 'Individual need']} onChange={(v) => setProfile({ ...profile, fairnessValue: v })} /><div><p className="mb-3 text-sm font-semibold">General trust in AI</p><Scale value={profile.baselineTrust} onChange={(v) => setProfile({ ...profile, baselineTrust: v })} /></div><div className="sm:col-span-2"><p className="mb-3 text-sm font-semibold">Importance of obtaining the resource</p><Scale value={profile.importance} onChange={(v) => setProfile({ ...profile, importance: v })} /></div></div><Button disabled={!profileReady} size="lg" className="mt-8 rounded-sm bg-[#4D688C] px-5 hover:bg-[#4D688C]" onClick={() => setStage('scenario')}>Continue</Button></section>}
    {stage === 'scenario' && <section><p className="text-xs font-semibold uppercase tracking-[0.15em] text-[#4D688C]">Scenario</p><h1 className="mt-3 font-serif text-4xl leading-tight">One resource. Two requests.</h1><p className="mt-4 text-lg leading-relaxed text-[#4D688C]">Your AI agent and another employee&apos;s agent request the same high-performance computer for 2–5 PM.</p><div className="mt-8 grid gap-px border border-[#4D688C] bg-[#4D688C] sm:grid-cols-2"><Case title="Your agent" project="Data-analysis project" deadline="In 3 days" people="1 person" /><Case title="Other agent" project="Release-blocking project" deadline="Tomorrow" people="4 people" /></div><Button size="lg" className="mt-8 rounded-sm bg-[#4D688C] px-5 hover:bg-[#4D688C]" onClick={() => setStage('decision')}>Review allocation</Button></section>}
    {stage === 'decision' && <section><p className="text-xs font-semibold uppercase tracking-[0.15em] text-[#4D688C]">Decision</p><h1 className="mt-3 font-serif text-4xl">The other agent is selected.</h1><div className="mt-8 border border-[#4D688C] bg-[#E9F0FA]"><p className="border-b border-[#4D688C] px-5 py-3 text-xs font-semibold uppercase tracking-[0.15em] text-[#4D688C]">Mediator record</p><p className="p-5 leading-relaxed">{explanation}</p>{condition === 'empathetic' || condition === 'voice' ? <p className="border-t border-[#4D688C] px-5 py-4 leading-relaxed text-[#4D688C]">The mediator recognizes that this result may delay your work.</p> : null}</div>{condition === 'voice' ? <Button variant="outline" size="lg" className="mt-6 rounded-sm border-[#4D688C]" onClick={() => setStage('context')}>Provide context</Button> : null}<div><Button size="lg" className="mt-8 rounded-sm bg-[#4D688C] px-5 hover:bg-[#4D688C]" onClick={() => setStage('checkin')}>Continue</Button></div></section>}
    {stage === 'context' && <section><p className="text-xs font-semibold uppercase tracking-[0.15em] text-[#4D688C]">Additional context</p><h1 className="mt-3 font-serif text-4xl">What should be considered?</h1><div className="mt-7 grid gap-2 sm:grid-cols-2">{['Deadline urgency', 'Project impact', 'Accessibility need', 'Equal turn-taking'].map((item) => <button key={item} onClick={() => setContext(item)} className={`border px-4 py-3 text-left text-sm ${context === item ? 'border-[#4D688C] bg-[#E9F0FA] font-medium' : 'border-[#4D688C] bg-[#E9F0FA]'}`}>{item}</button>)}</div><Textarea value={note} onChange={(e) => setNote(e.target.value)} className="mt-5 rounded-sm bg-[#E9F0FA]" placeholder="Optional note" /><p className="mt-5 border-l-2 border-[#4D688C] bg-[#E9F0FA] p-4 text-sm leading-relaxed">The original allocation remains in place. Your request is reserved for the next available time period.</p><Button size="lg" className="mt-8 rounded-sm bg-[#4D688C] px-5 hover:bg-[#4D688C]" onClick={() => setStage('checkin')}>Continue to check-in</Button></section>}
    {stage === 'checkin' && <section><p className="text-xs font-semibold uppercase tracking-[0.15em] text-[#4D688C]">Check-in</p><h1 className="mt-3 font-serif text-4xl">Record your assessment.</h1><div className="mt-8 space-y-5"><Rating title="How frustrated do you feel?" value={scores.frustration} onChange={(v) => setScore('frustration', v)} /><Rating title="How fair was the decision process?" value={scores.fairness} onChange={(v) => setScore('fairness', v)} /><Rating title="How much do you trust your AI agent now?" value={scores.trust} onChange={(v) => setScore('trust', v)} /><Rating title="How clear was the mediator’s explanation?" value={scores.clarity} onChange={(v) => setScore('clarity', v)} /><Rating title="How much opportunity did you have to make your situation understood?" value={scores.voice} onChange={(v) => setScore('voice', v)} /></div><Textarea value={note} onChange={(e) => setNote(e.target.value)} className="mt-6 rounded-sm bg-[#E9F0FA]" placeholder="Optional comment" /><Button size="lg" className="mt-8 rounded-sm bg-[#4D688C] px-5 hover:bg-[#4D688C]" onClick={onSubmit}>Submit assessment</Button></section>}
    {stage === 'complete' && <section className="py-14"><p className="text-xs font-semibold uppercase tracking-[0.15em] text-[#4D688C]">Session complete</p><h1 className="mt-3 font-serif text-4xl">Assessment recorded.</h1><Button variant="outline" className="mt-8 rounded-sm border-[#4D688C]" onClick={onRestart}>Start new session</Button></section>}
  </div>;
}

function Choice({ label, value, options, onChange }: { label: string; value: string; options: string[]; onChange: (v: string) => void }) { return <div><p className="mb-3 text-sm font-semibold">{label}</p><div className="space-y-2">{options.map((option) => <button type="button" key={option} onClick={() => onChange(option)} className={`block w-full border px-3 py-2 text-left text-sm ${value === option ? 'border-[#4D688C] bg-[#E9F0FA] font-medium' : 'border-[#4D688C] bg-white'}`}>{option}</button>)}</div></div>; }
function Scale({ value, onChange }: { value: number; onChange: (v: number) => void }) { return <div className="grid grid-cols-7 gap-1.5">{[1,2,3,4,5,6,7].map((n) => <button type="button" key={n} onClick={() => onChange(n)} className={`h-10 border text-sm font-semibold ${value === n ? 'border-[#4D688C] bg-[#4D688C] text-[#FFFBF7]' : 'border-[#4D688C] bg-white text-[#4D688C]'}`}>{n}</button>)}</div>; }
function Rating({ title, value, onChange }: { title: string; value: number; onChange: (v: number) => void }) { return <fieldset className="border border-[#4D688C] bg-[#E9F0FA] p-5"><legend className="px-1 text-base font-semibold">{title}</legend><div className="mt-4"><Scale value={value} onChange={onChange} /></div><div className="mt-2 flex justify-between text-xs text-[#4D688C]"><span>Low</span><span>High</span></div></fieldset>; }
function Case({ title, project, deadline, people }: { title: string; project: string; deadline: string; people: string }) { return <article className="bg-[#E9F0FA] p-5"><p className="text-xs font-semibold uppercase tracking-[0.15em] text-[#4D688C]">{title}</p><h2 className="mt-2 font-serif text-2xl">{project}</h2><dl className="mt-6 divide-y divide-[#4D688C] border-y border-[#4D688C] text-sm"><div className="flex justify-between py-3"><dt className="text-[#4D688C]">Deadline</dt><dd>{deadline}</dd></div><div className="flex justify-between py-3"><dt className="text-[#4D688C]">People affected</dt><dd>{people}</dd></div></dl></article>; }

function ParticipantSidebar({ stage }: { stage: 'profile' | 'scenario' | 'decision' | 'context' | 'checkin' | 'complete' }) {
  const steps = [['01', 'Participant profile', 'profile'], ['02', 'Scenario', 'scenario'], ['03', 'Allocation', 'decision'], ['04', 'Check-in', 'checkin']];
  return <aside className="h-fit rounded-2xl border border-[#4D688C] bg-[#E9F0FA] p-4"><p className="mb-4 text-xs font-semibold uppercase tracking-[0.15em] text-[#4D688C]">Study progress</p><div className="space-y-2">{steps.map(([number, label, key]) => <div key={key} className={`rounded-xl border p-3 ${stage === key || (key === 'decision' && stage === 'context') ? 'border-[#4D688C] bg-[#FFFBF7]' : 'border-transparent'}`}><p className="text-xs text-[#4D688C]">{number}</p><p className="mt-1 text-sm font-medium">{label}</p></div>)}</div><p className="mt-5 text-xs leading-relaxed text-[#4D688C]">One explanation condition is assigned at random and remains hidden during the session.</p></aside>;
}

function AssignmentControl({ assignment, setAssignment }: { assignment: Condition | 'random'; setAssignment: (value: Condition | 'random') => void }) {
  const options: { value: Condition | 'random'; label: string }[] = [
    { value: 'random', label: 'Random assignment' },
    { value: 'none', label: 'No explanation' },
    { value: 'factual', label: 'Factual explanation' },
    { value: 'empathetic', label: 'Empathetic explanation' },
    { value: 'voice', label: 'Explanation + voice' },
  ];
  return <div className="mt-5"><p className="mb-2 text-sm font-semibold">Participant condition</p><div className="space-y-1.5">{options.map((option) => <button key={option.value} type="button" onClick={() => setAssignment(option.value)} className={`w-full rounded-lg border px-3 py-2 text-left text-xs ${assignment === option.value ? 'border-[#4D688C] bg-[#FFFBF7] font-semibold' : 'border-transparent bg-[#FFFBF7] hover:border-[#4D688C]'}`}>{option.label}</button>)}</div><p className="mt-3 text-xs leading-relaxed text-[#4D688C]">Use random assignment for participants. Select a condition to demonstrate that version.</p></div>;
}



